-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 05, 2022 at 03:46 PM
-- Server version: 10.4.21-MariaDB
-- PHP Version: 7.4.23

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `nasa`
--

-- --------------------------------------------------------

--
-- Table structure for table `pictureoftheday`
--

CREATE TABLE `pictureoftheday` (
  `id` int(11) NOT NULL,
  `date` date NOT NULL,
  `title` varchar(300) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `description` varchar(300) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `image` varchar(300) COLLATE utf8mb4_unicode_520_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

--
-- Dumping data for table `pictureoftheday`
--

INSERT INTO `pictureoftheday` (`id`, `date`, `title`, `description`, `image`) VALUES
(1, '2022-03-07', 'A Lion in Orion', 'Yes, but can you see the lion? A deep exposure shows the famous dark indentation that looks like a horse\'s head, visible just left and below center, and known unsurprisingly as the Horsehead Nebula.  The Horsehead Nebula (Barnard 33) is part of a vast complex of dark absorbing dust and bright glowin', 'https://apod.nasa.gov/apod/image/2203/HorseFlameLion_Mahfoud_960.jpg'),
(2, '2022-03-08', 'Moon in Inverted Colors', 'Which moon is this? It\'s Earth\'s moon -- but in inverted colors. Here, the pixel values corresponding to light and dark areas have been translated in reverse, or inverted, producing a false-color representation reminiscent of a black and white photographic negative.  However, this is an inverted col', 'https://apod.nasa.gov/apod/image/2203/InvertedMoon_Glawdzin_960.jpg'),
(3, '2022-03-09', 'A Flower-Shaped Rock on Mars', 'It is one of the more unusual rocks yet found on Mars. Smaller than a penny, the rock has several appendages that make it look, to some, like a flower. Although it would be a major discovery if the rock was truly a fossilized ancient Martian flower, there are less spectacular -- and currently prefer', 'https://apod.nasa.gov/apod/image/2203/FlowerRock_Curiosity_960.jpg'),
(4, '2022-03-10', 'Globular Star Cluster 47 Tuc', 'Globular star cluster 47 Tucanae is a jewel of the southern sky. Also known as NGC 104, it roams the halo of our Milky Way Galaxy along with some 200 other globular star clusters. The second brightest globular cluster (after Omega Centauri) as seen from planet Earth, 47 Tuc lies about 13,000 light-y', 'https://apod.nasa.gov/apod/image/2203/NGC104_TL_PS1_INSIGHT1024.jpg'),
(5, '2022-03-11', 'When Rainbows Smile', 'Want to see a rainbow smile? Look near the zenith (straight up) when the sun is low in the sky and you might. This example of an ice halo known as a circumzenithal arc was captured above a palm tree top from Ragusa, Sicily on February 24. The vividly colorful arcs are often called smiling rainbows b', 'https://apod.nasa.gov/apod/image/2203/ArcoCircumzenitale_1024c.jpg'),
(6, '2022-03-12', 'Point Reyes Milky Way', 'Northern winter constellations and a long arc of the Milky Way are setting in this night skyscape looking toward the Pacific Ocean from Point Reyes on planet Earth\'s California coast. Sirius, alpha star of Canis Major, is prominent below the starry arc toward the left. Orion\'s yellowish Betelgeuse, ', 'https://apod.nasa.gov/apod/image/2203/PointReyesMilkyWayDanZafra1024.jpg'),
(7, '2022-03-13', 'Colorful Airglow Bands Surround Milky Way', 'Why would the sky glow like a giant repeating rainbow?  Airglow.  Now air glows all of the time, but it is usually hard to see. A disturbance however -- like an approaching storm -- may cause noticeable rippling in the Earth\'s atmosphere. These gravity waves are oscillations in air analogous to thos', 'https://apod.nasa.gov/apod/image/2203/AirglowRings_Wang_1080.jpg'),
(8, '2022-03-14', 'Star Formation in the Eagle Nebula', 'Where do stars form?  One place, star forming regions known as \"EGGs\", are being uncovered at the end of this giant pillar of gas and dust in the Eagle Nebula (M16).  Short for evaporating gaseous globules, EGGs are dense regions of mostly molecular hydrogen gas that fragment and gravitationally col', 'https://apod.nasa.gov/apod/image/2203/Pillars_HstBibillo_1097.jpg'),
(9, '2022-03-15', 'A Road to the Stars', 'Pictured -- a very scenic road to the stars.  The road approaches La Silla Observatory in Chile, with the ESO\'s 3.6-meter telescope just up ahead. To the left are some futuristic-looking support structures for the planned BlackGEM telescopes, an array of optical telescopes that will help locate opti', 'https://apod.nasa.gov/apod/image/2203/Road2Stars_EsoHoralek_1080.jpg'),
(10, '2022-03-16', 'The Observable Universe', 'How far can you see? Everything you can see, and everything you could possibly see, right now, assuming your eyes could detect all types of radiations around you -- is the observable universe.  In light, the farthest we can see comes from the cosmic microwave background, a time 13.8 billion years ag', 'https://apod.nasa.gov/apod/image/2203/VisUni_WikiBudassi_960.jpg'),
(11, '2022-03-17', 'Centaurus A', 'A mere 11 million light-years away, Centaurus A is the closest active galaxy to planet Earth. Spanning over 60,000 light-years, the peculiar elliptical galaxy also known as NGC 5128, is featured in this sharp telescopic view. Centaurus A is apparently the result of a collision of two otherwise norma', 'https://apod.nasa.gov/apod/image/2203/CentaurusA_DavidAlemazkour1024.jpg'),
(12, '2022-03-18', 'A Filament in Monoceros', 'Bluish reflection nebulae seem to fill this dusty expanse. The sharp telescopic frame spans over 1 degree on the sky toward the faint but fanciful constellation Monoceros, the Unicorn. Seen within the Monoceros R1 cloud complex some 2,500 light-years away, bluish IC 447 is on the left, joined by a l', 'https://apod.nasa.gov/apod/image/2203/IC447_446GiorgioFerrari1024.jpg'),
(13, '2022-03-19', '2MASS J17554042+6551277', '2MASS J17554042+6551277 doesn\'t exactly roll off the tongue but that\'s the name, a coordinate-based catalog designation, of the star centered in this sharp field of view. Fans of the distant universe should get used to its spiky appearance though. The diffraction pattern is created by the 18 hexagon', 'https://apod.nasa.gov/apod/image/2203/telescope_alignment_evaluation_image_labeled1024.jpg'),
(14, '2022-03-20', 'A Picturesque Equinox Sunset', 'What\'s that at the end of the road? The Sun. Many towns have roads that run east - west, and on two days each year, the Sun rises and sets right down the middle. Today is one of those days: an equinox. Not only is today a day of equal night (\"aequus\"-\"nox\") and day time, but also a day when the sun ', 'https://apod.nasa.gov/apod/image/2203/EquinoxSunset_Christen_960.jpg'),
(15, '2022-03-21', 'The Sky in 2021', 'What if you could see the entire sky -- all at once -- for an entire year? That, very nearly, is what is pictured here.  Every 15 minutes during 2021, an all-sky camera took an image of the sky over the Netherlands. Central columns from these images were then aligned and combined to create the featu', 'https://apod.nasa.gov/apod/image/2203/YearOfSky_Bassa_960.jpg'),
(16, '2022-03-22', 'A Whale of an Aurora over Swedish Forest', 'What\'s that in the sky? An aurora. A large coronal mass ejection occurred on our Sun earlier this month, throwing a cloud of fast-moving electrons, protons, and ions toward the Earth. Part of this cloud impacted our Earth\'s magnetosphere and, bolstered by a sudden gap, resulted in spectacular aurora', 'https://apod.nasa.gov/apod/image/2203/WhaleAurora_Strand_960.jpg'),
(17, '2022-03-23', 'The Bubble Nebula from Hubble', 'Massive stars can blow bubbles.  The featured image shows perhaps the most famous of all star-bubbles, NGC 7635, also known simply as The Bubble Nebula. Although it looks delicate, the 7-light-year diameter bubble offers evidence of violent processes at work. Above and left of the Bubble\'s center is', 'https://apod.nasa.gov/apod/image/2203/Bubble_HubbleOzsarac_960.jpg'),
(18, '2022-03-24', 'Arp 78: Peculiar Galaxy in Aries', 'Peculiar spiral galaxy Arp 78 is found within the boundaries of the head strong constellation Aries. Some 100 million light-years beyond the stars and nebulae of our Milky Way galaxy, the island universe is over 100,000 light-years across. Also known as NGC 772, it sports a prominent, outer spiral a', 'https://apod.nasa.gov/apod/image/2203/noirlab2209a_ngc772_1024.jpg'),
(19, '2022-03-25', 'The Medusa Nebula', 'Braided and serpentine filaments of glowing gas suggest this nebula\'s popular name, The Medusa Nebula. Also known as Abell 21, this Medusa is an old planetary nebula some 1,500 light-years away in the constellation Gemini. Like its mythological namesake, the nebula is associated with a dramatic tran', 'https://apod.nasa.gov/apod/image/2203/Medusa_Nebula_141_x_180s.jpg'),
(20, '2022-03-26', 'Pluto at Night', 'The night side of Pluto spans this shadowy scene. In the stunning spacebased perspective the Sun is 4.9 billion kilometers (almost 4.5 light-hours) behind the dim and distant world. It was captured by far flung New Horizons in July of 2015 when the spacecraft was at a range of some 21,000 kilometers', 'https://apod.nasa.gov/apod/image/2203/PIA20727PlutoNight1024c.jpg'),
(21, '2022-03-27', 'Titan Seas Reflect Sunlight', 'Why would the surface of Titan light up with a blinding flash? The reason: a sunglint from liquid seas.  Saturn\'s moon Titan has numerous smooth lakes of methane that, when the angle is right, reflect sunlight as if they were mirrors.  Pictured here in false-color, the robotic Cassini spacecraft tha', 'https://apod.nasa.gov/apod/image/2203/TitanGlint_cassini_960.jpg'),
(22, '2022-03-28', 'Gems of a Maldivean Night', 'The southernmost part of the Milky Way contains not only the stars of the Southern Cross, but the closest star system to our Sun -- Alpha Centauri.  The Southern Cross itself is topped by the bright, yellowish star Gamma Crucis.  A line from Gamma Crucis through the blue star at the bottom of the cr', 'https://apod.nasa.gov/apod/image/2203/SouthIsland_Horalek_960.jpg'),
(23, '2022-03-29', 'Venus and Mars: Passing in the Night', 'When two planets pass on the night sky, they can usually be seen near each other for a week or more. In the case of this planetary conjunction, Venus and Mars passed within 4 degrees of each other earlier this month. The featured image was taken a few days prior, when Venus was slowing rising in the', 'https://apod.nasa.gov/apod/image/2203/VenusMars_Fairbairn_960.jpg'),
(24, '2022-03-30', 'Animation: Odd Radio Circles', 'What do you call a cosmic puzzle that no one expected to see?  In this case, Odd Radio Circles, aka ORCs.  ORC-1 typifies the enigmatic five objects, only visible at radio frequencies, that were serendipitously discovered in 2019 using the new Australian SKA Pathfinder radio array.  The final image ', 'https://www.youtube.com/embed/m8qvOpcDt1o?rel=0'),
(25, '2022-03-31', 'Exploring the Antennae', 'Some 60 million light-years away in the southerly constellation Corvus, two large galaxies are colliding. Stars in the two galaxies, cataloged as NGC 4038 and NGC 4039, very rarely collide in the course of the ponderous cataclysm that lasts for hundreds of millions of years. But the galaxies\' large ', 'https://apod.nasa.gov/apod/image/2203/Arp244-LRGB1024.jpg'),
(26, '2022-04-01', 'Leaning Tower, Active Sun', 'The natural filter of a hazy atmosphere offered this recognizable architecture and sunset telephoto view on March 27. Dark against the solar disk, large sunspots in solar active regions 2975 and 2976 are wedged between the Duomo of Pisa and its famous Leaning Tower. Only one day later, Sun-staring s', 'https://apod.nasa.gov/apod/image/2204/sunspotsleaningtowerofpisa1024.jpg'),
(27, '2022-04-02', 'Nova Scotia Northern Lights', 'This almost otherworldly display of northern lights was captured in clear skies during the early hours of March 31 from 44 degrees north latitude, planet Earth. In a five second exposure the scene looks north from Martinique Beach Provincial Park in Nova Scotia, Canada. Stars of the W-shaped constel', 'https://apod.nasa.gov/apod/image/2204/Z62_5747-Edit1090.jpg'),
(28, '2022-04-03', 'CMB Dipole: Speeding Through the Universe', 'Our Earth is not at rest.  The Earth moves around the Sun.  The Sun orbits the center of the Milky Way Galaxy.  The Milky Way Galaxy orbits in the Local Group of Galaxies.  The Local Group falls toward the Virgo Cluster of Galaxies.  But these speeds are less than the speed that all of these objects', 'https://apod.nasa.gov/apod/image/2204/CmbDipole_cobe_960.jpg'),
(29, '2022-04-04', 'A Vortex Aurora over Iceland', 'No, the car was not in danger of being vacuumed into space by the big sky vortex. For one reason, the vortex was really an aurora, and since auroras are created by particles striking the Earth from space, they do not create a vacuum. This rapidly developing auroral display was caused by a Coronal Ma', 'https://apod.nasa.gov/apod/image/2204/VortexAurora_Suarez_1080.jpg'),
(30, '2022-04-05', 'Seven Sisters versus California', 'On the upper right, dressed in blue, is the Pleiades.  Also known as the Seven Sisters and M45, the Pleiades is one of the brightest and most easily visible open clusters on the sky. The Pleiades contains over 3,000 stars, is about 400 light years away, and only 13 light years across. Surrounding th', 'https://apod.nasa.gov/apod/image/2204/Calif2Pleiades_Krcmarek_1080.jpg'),
(31, '2022-03-07', 'A Lion in Orion', 'Yes, but can you see the lion? A deep exposure shows the famous dark indentation that looks like a horse\'s head, visible just left and below center, and known unsurprisingly as the Horsehead Nebula.  The Horsehead Nebula (Barnard 33) is part of a vast complex of dark absorbing dust and bright glowin', 'https://apod.nasa.gov/apod/image/2203/HorseFlameLion_Mahfoud_960.jpg'),
(32, '2022-03-08', 'Moon in Inverted Colors', 'Which moon is this? It\'s Earth\'s moon -- but in inverted colors. Here, the pixel values corresponding to light and dark areas have been translated in reverse, or inverted, producing a false-color representation reminiscent of a black and white photographic negative.  However, this is an inverted col', 'https://apod.nasa.gov/apod/image/2203/InvertedMoon_Glawdzin_960.jpg'),
(33, '2022-03-09', 'A Flower-Shaped Rock on Mars', 'It is one of the more unusual rocks yet found on Mars. Smaller than a penny, the rock has several appendages that make it look, to some, like a flower. Although it would be a major discovery if the rock was truly a fossilized ancient Martian flower, there are less spectacular -- and currently prefer', 'https://apod.nasa.gov/apod/image/2203/FlowerRock_Curiosity_960.jpg'),
(34, '2022-03-10', 'Globular Star Cluster 47 Tuc', 'Globular star cluster 47 Tucanae is a jewel of the southern sky. Also known as NGC 104, it roams the halo of our Milky Way Galaxy along with some 200 other globular star clusters. The second brightest globular cluster (after Omega Centauri) as seen from planet Earth, 47 Tuc lies about 13,000 light-y', 'https://apod.nasa.gov/apod/image/2203/NGC104_TL_PS1_INSIGHT1024.jpg'),
(35, '2022-03-11', 'When Rainbows Smile', 'Want to see a rainbow smile? Look near the zenith (straight up) when the sun is low in the sky and you might. This example of an ice halo known as a circumzenithal arc was captured above a palm tree top from Ragusa, Sicily on February 24. The vividly colorful arcs are often called smiling rainbows b', 'https://apod.nasa.gov/apod/image/2203/ArcoCircumzenitale_1024c.jpg'),
(36, '2022-03-12', 'Point Reyes Milky Way', 'Northern winter constellations and a long arc of the Milky Way are setting in this night skyscape looking toward the Pacific Ocean from Point Reyes on planet Earth\'s California coast. Sirius, alpha star of Canis Major, is prominent below the starry arc toward the left. Orion\'s yellowish Betelgeuse, ', 'https://apod.nasa.gov/apod/image/2203/PointReyesMilkyWayDanZafra1024.jpg'),
(37, '2022-03-13', 'Colorful Airglow Bands Surround Milky Way', 'Why would the sky glow like a giant repeating rainbow?  Airglow.  Now air glows all of the time, but it is usually hard to see. A disturbance however -- like an approaching storm -- may cause noticeable rippling in the Earth\'s atmosphere. These gravity waves are oscillations in air analogous to thos', 'https://apod.nasa.gov/apod/image/2203/AirglowRings_Wang_1080.jpg'),
(38, '2022-03-14', 'Star Formation in the Eagle Nebula', 'Where do stars form?  One place, star forming regions known as \"EGGs\", are being uncovered at the end of this giant pillar of gas and dust in the Eagle Nebula (M16).  Short for evaporating gaseous globules, EGGs are dense regions of mostly molecular hydrogen gas that fragment and gravitationally col', 'https://apod.nasa.gov/apod/image/2203/Pillars_HstBibillo_1097.jpg'),
(39, '2022-03-15', 'A Road to the Stars', 'Pictured -- a very scenic road to the stars.  The road approaches La Silla Observatory in Chile, with the ESO\'s 3.6-meter telescope just up ahead. To the left are some futuristic-looking support structures for the planned BlackGEM telescopes, an array of optical telescopes that will help locate opti', 'https://apod.nasa.gov/apod/image/2203/Road2Stars_EsoHoralek_1080.jpg'),
(40, '2022-03-16', 'The Observable Universe', 'How far can you see? Everything you can see, and everything you could possibly see, right now, assuming your eyes could detect all types of radiations around you -- is the observable universe.  In light, the farthest we can see comes from the cosmic microwave background, a time 13.8 billion years ag', 'https://apod.nasa.gov/apod/image/2203/VisUni_WikiBudassi_960.jpg'),
(41, '2022-03-17', 'Centaurus A', 'A mere 11 million light-years away, Centaurus A is the closest active galaxy to planet Earth. Spanning over 60,000 light-years, the peculiar elliptical galaxy also known as NGC 5128, is featured in this sharp telescopic view. Centaurus A is apparently the result of a collision of two otherwise norma', 'https://apod.nasa.gov/apod/image/2203/CentaurusA_DavidAlemazkour1024.jpg'),
(42, '2022-03-18', 'A Filament in Monoceros', 'Bluish reflection nebulae seem to fill this dusty expanse. The sharp telescopic frame spans over 1 degree on the sky toward the faint but fanciful constellation Monoceros, the Unicorn. Seen within the Monoceros R1 cloud complex some 2,500 light-years away, bluish IC 447 is on the left, joined by a l', 'https://apod.nasa.gov/apod/image/2203/IC447_446GiorgioFerrari1024.jpg'),
(43, '2022-03-19', '2MASS J17554042+6551277', '2MASS J17554042+6551277 doesn\'t exactly roll off the tongue but that\'s the name, a coordinate-based catalog designation, of the star centered in this sharp field of view. Fans of the distant universe should get used to its spiky appearance though. The diffraction pattern is created by the 18 hexagon', 'https://apod.nasa.gov/apod/image/2203/telescope_alignment_evaluation_image_labeled1024.jpg'),
(44, '2022-03-20', 'A Picturesque Equinox Sunset', 'What\'s that at the end of the road? The Sun. Many towns have roads that run east - west, and on two days each year, the Sun rises and sets right down the middle. Today is one of those days: an equinox. Not only is today a day of equal night (\"aequus\"-\"nox\") and day time, but also a day when the sun ', 'https://apod.nasa.gov/apod/image/2203/EquinoxSunset_Christen_960.jpg'),
(45, '2022-03-21', 'The Sky in 2021', 'What if you could see the entire sky -- all at once -- for an entire year? That, very nearly, is what is pictured here.  Every 15 minutes during 2021, an all-sky camera took an image of the sky over the Netherlands. Central columns from these images were then aligned and combined to create the featu', 'https://apod.nasa.gov/apod/image/2203/YearOfSky_Bassa_960.jpg'),
(46, '2022-03-22', 'A Whale of an Aurora over Swedish Forest', 'What\'s that in the sky? An aurora. A large coronal mass ejection occurred on our Sun earlier this month, throwing a cloud of fast-moving electrons, protons, and ions toward the Earth. Part of this cloud impacted our Earth\'s magnetosphere and, bolstered by a sudden gap, resulted in spectacular aurora', 'https://apod.nasa.gov/apod/image/2203/WhaleAurora_Strand_960.jpg'),
(47, '2022-03-23', 'The Bubble Nebula from Hubble', 'Massive stars can blow bubbles.  The featured image shows perhaps the most famous of all star-bubbles, NGC 7635, also known simply as The Bubble Nebula. Although it looks delicate, the 7-light-year diameter bubble offers evidence of violent processes at work. Above and left of the Bubble\'s center is', 'https://apod.nasa.gov/apod/image/2203/Bubble_HubbleOzsarac_960.jpg'),
(48, '2022-03-24', 'Arp 78: Peculiar Galaxy in Aries', 'Peculiar spiral galaxy Arp 78 is found within the boundaries of the head strong constellation Aries. Some 100 million light-years beyond the stars and nebulae of our Milky Way galaxy, the island universe is over 100,000 light-years across. Also known as NGC 772, it sports a prominent, outer spiral a', 'https://apod.nasa.gov/apod/image/2203/noirlab2209a_ngc772_1024.jpg'),
(49, '2022-03-25', 'The Medusa Nebula', 'Braided and serpentine filaments of glowing gas suggest this nebula\'s popular name, The Medusa Nebula. Also known as Abell 21, this Medusa is an old planetary nebula some 1,500 light-years away in the constellation Gemini. Like its mythological namesake, the nebula is associated with a dramatic tran', 'https://apod.nasa.gov/apod/image/2203/Medusa_Nebula_141_x_180s.jpg'),
(50, '2022-03-26', 'Pluto at Night', 'The night side of Pluto spans this shadowy scene. In the stunning spacebased perspective the Sun is 4.9 billion kilometers (almost 4.5 light-hours) behind the dim and distant world. It was captured by far flung New Horizons in July of 2015 when the spacecraft was at a range of some 21,000 kilometers', 'https://apod.nasa.gov/apod/image/2203/PIA20727PlutoNight1024c.jpg'),
(51, '2022-03-27', 'Titan Seas Reflect Sunlight', 'Why would the surface of Titan light up with a blinding flash? The reason: a sunglint from liquid seas.  Saturn\'s moon Titan has numerous smooth lakes of methane that, when the angle is right, reflect sunlight as if they were mirrors.  Pictured here in false-color, the robotic Cassini spacecraft tha', 'https://apod.nasa.gov/apod/image/2203/TitanGlint_cassini_960.jpg'),
(52, '2022-03-28', 'Gems of a Maldivean Night', 'The southernmost part of the Milky Way contains not only the stars of the Southern Cross, but the closest star system to our Sun -- Alpha Centauri.  The Southern Cross itself is topped by the bright, yellowish star Gamma Crucis.  A line from Gamma Crucis through the blue star at the bottom of the cr', 'https://apod.nasa.gov/apod/image/2203/SouthIsland_Horalek_960.jpg'),
(53, '2022-03-29', 'Venus and Mars: Passing in the Night', 'When two planets pass on the night sky, they can usually be seen near each other for a week or more. In the case of this planetary conjunction, Venus and Mars passed within 4 degrees of each other earlier this month. The featured image was taken a few days prior, when Venus was slowing rising in the', 'https://apod.nasa.gov/apod/image/2203/VenusMars_Fairbairn_960.jpg'),
(54, '2022-03-30', 'Animation: Odd Radio Circles', 'What do you call a cosmic puzzle that no one expected to see?  In this case, Odd Radio Circles, aka ORCs.  ORC-1 typifies the enigmatic five objects, only visible at radio frequencies, that were serendipitously discovered in 2019 using the new Australian SKA Pathfinder radio array.  The final image ', 'https://www.youtube.com/embed/m8qvOpcDt1o?rel=0'),
(55, '2022-03-31', 'Exploring the Antennae', 'Some 60 million light-years away in the southerly constellation Corvus, two large galaxies are colliding. Stars in the two galaxies, cataloged as NGC 4038 and NGC 4039, very rarely collide in the course of the ponderous cataclysm that lasts for hundreds of millions of years. But the galaxies\' large ', 'https://apod.nasa.gov/apod/image/2203/Arp244-LRGB1024.jpg'),
(56, '2022-04-01', 'Leaning Tower, Active Sun', 'The natural filter of a hazy atmosphere offered this recognizable architecture and sunset telephoto view on March 27. Dark against the solar disk, large sunspots in solar active regions 2975 and 2976 are wedged between the Duomo of Pisa and its famous Leaning Tower. Only one day later, Sun-staring s', 'https://apod.nasa.gov/apod/image/2204/sunspotsleaningtowerofpisa1024.jpg'),
(57, '2022-04-02', 'Nova Scotia Northern Lights', 'This almost otherworldly display of northern lights was captured in clear skies during the early hours of March 31 from 44 degrees north latitude, planet Earth. In a five second exposure the scene looks north from Martinique Beach Provincial Park in Nova Scotia, Canada. Stars of the W-shaped constel', 'https://apod.nasa.gov/apod/image/2204/Z62_5747-Edit1090.jpg'),
(58, '2022-04-03', 'CMB Dipole: Speeding Through the Universe', 'Our Earth is not at rest.  The Earth moves around the Sun.  The Sun orbits the center of the Milky Way Galaxy.  The Milky Way Galaxy orbits in the Local Group of Galaxies.  The Local Group falls toward the Virgo Cluster of Galaxies.  But these speeds are less than the speed that all of these objects', 'https://apod.nasa.gov/apod/image/2204/CmbDipole_cobe_960.jpg'),
(59, '2022-04-04', 'A Vortex Aurora over Iceland', 'No, the car was not in danger of being vacuumed into space by the big sky vortex. For one reason, the vortex was really an aurora, and since auroras are created by particles striking the Earth from space, they do not create a vacuum. This rapidly developing auroral display was caused by a Coronal Ma', 'https://apod.nasa.gov/apod/image/2204/VortexAurora_Suarez_1080.jpg'),
(60, '2022-04-05', 'Seven Sisters versus California', 'On the upper right, dressed in blue, is the Pleiades.  Also known as the Seven Sisters and M45, the Pleiades is one of the brightest and most easily visible open clusters on the sky. The Pleiades contains over 3,000 stars, is about 400 light years away, and only 13 light years across. Surrounding th', 'https://apod.nasa.gov/apod/image/2204/Calif2Pleiades_Krcmarek_1080.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `pictureoftheday`
--
ALTER TABLE `pictureoftheday`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `pictureoftheday`
--
ALTER TABLE `pictureoftheday`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=61;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
